name: Build Packages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build deb
        run: |
          mkdir -p .debpkg/usr/share/cockpit
          cp ./navigator .debpkg/usr/share/cockpit
      - uses: jiro4989/build-deb-action@v2
        with:
          package: navigator
          package_root: .debpkg
          maintainer: david.cloutier@glatt.com
          version: 1.00
          arch: 'amd64'
          depends: 'cockpit'
          desc: 'this is a file navigator for cockpit'
          
          
